name: inclass8
description: A new Flutter project with local SQLite storage.
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.2
  path_provider: ^2.0.11
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
